version: '3.1'

services:
  php-app:
    build: ./
    entrypoint: ./.docker/entrypoint.sh
    container_name: my-php-app
    ports:
      - 8000:8000
    volumes:
      - ./:/home/php/myapp
    depends_on: 
      - db
    environment: 
      - MYSQL_USER=root
      - MYSQL_PASS=root
      - MY_HOST=db
      - DB_PDO_DRIVER=pdo_mysql
      - DB_HOST=db
      - DB_DSNAME=crud_jquery
      - DB_USER=root
      - DB_PASSWORD=root
  
  db:
    image: mysql
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - "./data:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data: